# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
mod_version=1.7.2
group=com.github.iunius118.chilibulletweapons
java_version=17

# Common
minecraft_version=1.19
mod_name=Chili Bullet Weapons
mod_author=Iunius118
mod_id=chilibulletweapons
license=MIT License
credits=
description=Adds chili peppers, foods and weapons.
minecraft_version_range=[1.19, 1.19.2]
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.19.2
parchment_version=2022.11.27

# Fabric
fabric_version=0.58.0+1.19
fabric_loader_version=0.19.3
cloth_config_version=8.3.134

# Forge
forge_version=41.1.0
forge_loader_version_range=[41,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
